services:
  www:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    container_name: Ecoride
    image: ecoride_img
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/dockersymfony
    restart: unless-stopped
  mariadb:
   image: mariadb:10.11
   restart: always
   container_name: mariadb
   environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
   volumes:
      - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data: