services:
  Php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    container_name: Ecoride
    image: elkaouri/ecorideapi
    ports:
      - "8000:80"
    environment:
      APP_ENV: ${APP_ENV}             
      APP_SECRET: ${APP_SECRET}       
      DATABASE_URL: ${DATABASE_URL}   
      MAILER_DSN: ${MAILER_DSN}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}


    volumes:
      - ./app:/var/www/html/Ecoride
    restart: unless-stopped
  mariadb:
   image: mariadb:10.11
   restart: always
   container_name: mariadb
   environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
   volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d

volumes:
    mariadb_data: