services:
  Ecoride:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecorideProd
    image: elkaouri/ecorideapi:1.22
    ports:
      - "80:80"
    environment:
      APP_ENV: ${APP_ENV}             
      APP_SECRET: ${APP_SECRET}       
      DATABASE_URL: ${DATABASE_URL}   
      MAILER_DSN: ${MAILER_DSN}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}

    restart: unless-stopped
  mariadb:
   image: mariadb:10.11
   restart: always
   container_name: mariadb
   environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
   volumes:
      - mariadb_data:/var/lib/mysql
 
volumes:
    mariadb_data: