vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_images:
            uri_prefix: /uploads/users
            upload_destination: "%kernel.project_dir%/public/uploads/users"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
